name: build software
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - 'software/**'

jobs:
  cassandra:
    name: "software:${{ matrix.cassandra }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cassandra:
          - cassandra_java11_python2
          - cassandra_java11_python3
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./software/cassandra/${{ matrix.cassandra }}
          file: ./software/cassandra/${{ matrix.cassandra }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/parkervcp/software:${{ matrix.cassandra }}

# Copy a job above and adjust it to enable the build of newly added software
