on:
  push:
    branches:
      - master
    paths-ignore:
      - games
      - installers

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: HEAD
          filters: |
            alpine: alpine
            go_1.14: go/1.14
            go_1.15: go/1.15
            go_1.16: go/1.16
            python_3.7: python/3.7
            python_3.8: python/3.8
            python_3.9: python/3.9
            nodejs_12: nodejs/12
            nodejs_13: nodejs/13
            nodejs_14: nodejs/14
            nodejs_15: nodejs/15
            java_7: java/7
            java_8: java/8
            java_9: java/9
            java_11: java/11
            java_14: java/14
            java_16: java/16

  push:
    needs: changes
    # name: "yolks:python_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.images) }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ matrix.image }}"
#      - uses: docker/setup-buildx-action@v1
#        with:
#          version: "v0.5.1"
#          buildkitd-flags: --debug
#      - uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.REGISTRY_TOKEN }}
#      - uses: docker/build-push-action@v2
#        with:
#          context: ./python
#          file: ./python/${{ matrix.tag }}/Dockerfile
#          platforms: linux/amd64
#          push: true
#          tags: |
#            ghcr.io/pterodactyl/yolks:python_${{ matrix.tag }}
